version: "3.8"
services:
  db:
    image: postgres:16.1-alpine
    volumes:
      - good_cheese_postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel verbose
    volumes: 
      - good_cheese_redis:/data
  api:
    stdin_open: true
    tty: true
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    command: poetry run uvicorn main:app --host=0.0.0.0 --reload
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
    links:
      - redis
  celery:
    stdin_open: true
    tty: true
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    command: poetry run celery -A src.tasks worker -l warning -E
    depends_on:
      - redis
    links:
      - redis
  app:
    stdin_open: true
    tty: true
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - ./node_modules:/app/node_modules
    command: bash -c "bun run dev"
    depends_on:
      - api
    ports:
      - "8888:8888"
    environment:
      BROWSER: /dev/null
  

volumes:
  good_cheese_postgresql:
  good_cheese_redis:
