"""Add government_id column to boleto

Revision ID: 524735005cca
Revises: a607cf06165e
Create Date: 2024-02-20 07:05:37.751955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '524735005cca'
down_revision: Union[str, None] = 'a607cf06165e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boletos', sa.Column('government_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boletos', 'government_id')
    # ### end Alembic commands ###
