"""Create File and Boleto Tables

Revision ID: a607cf06165e
Revises: 
Create Date: 2024-02-20 05:23:18.472745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a607cf06165e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boleto_files',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('checksum', sa.String(), nullable=False),
        sa.Column('size', sa.Integer(), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=False),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boletos',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('debt_amount', sa.Integer(), nullable=False),
        sa.Column('debt_due_date', sa.DateTime(), nullable=False),
        sa.Column('debt_id', sa.String(), nullable=False),
        sa.Column('processed_at', sa.DateTime(), nullable=True),
        sa.Column('boleto_file_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['boleto_file_id'], ['boleto_files.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.Index('boleto_debt_due_date', 'debt_due_date', postgresql_using='BRIN')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('boletos')
    op.drop_table('boleto_files')
    # ### end Alembic commands ###
